<?php

	class Country
	{
		public function __construct()
		{
		}
		
					// Anyone's Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames($args)
		{
			$language = $args[language];
			
			$get_country_names_function = 'GetTranslatedCountryNames_' . $language;
			
			return $this->$get_country_names_function();
		}
		
					// English (EN) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_en()
		{
			return [
				'de'=>
					[
						'Germany',
						'Austria',
						'Switzerland',
						'Liechtenstein',
					],
				'en'=>
					[
						'United States of America',
						'India',
						'Ireland',
						'Pakistan',
						'Nigeria',
						'England',
						'Australia',
						'Canada',
						'Ghana',
						'Malta',
						'Israel',
						'New Zealand',
						'Jamaica',
					],
				'es'=>
					[
						'Spain',
						'Cuba',
						'Mexico',
						'Colombia',
						'Argentina',
						'Peru',
						'Venezuela',
						'Chile',
						'Ecuador',
						'Guatemala',
						'Bolivia',
						'Dominican Republic',
						'Honduras',
						'Paraguay',
						'El Salvador',
						'Nicaragua',
						'Costa Rica',
						'Puerto Rico',
						'Panama',
						'Uruguay',
						'Guyana',
						'Equatorial Guinea',
						'Andorra',
						'Belize',
					],
				'fr'=>
					[
						'France',
						'Canada',
						'Madagascar',
						'Cameroon',
						'Ivory Coast',
						'Burkina Faso',
						'Niger',
						'Senegal',
						'Mali',
						'Rwanda',
						'Belgium',
						'Haiti',
						'Chad',
						'Guinea',
						'Burundi',
						'Benin',
						'Switzerland',
						'Togo',
						'Central African Republic',
						'Republic of the Congo',
						'Gabon',
						'Comoros',
						'Equatorial Guinea',
						'French Polynesia',
						'French Guiana',
						'New Caledonia',
						'Aosta Valley',
						'Jersey',
						'Guernsey',
						'Monaco',
						'Saint-Martin',
						'Wallis and Futuna',
						'Saint-Barthélemy',
					],
				'ja'=>
					[
						'Japan',
					],
				'it'=>
					[
						'Italy',
						'Malta',
						'San Marino',
						'Switzerland',
						'Croatia',
						'Slovenia',
					],
				'nl'=>
					[
						'Netherlands',
						'Belgium',
						'Suriname',
						'South Africa',
						'Aruba',
						'Curaçao',
						'Republic of Namibia',
						'Bonaire',
						'Saba',
						'Sint Eustatius',
						'Sint Maarten',
					],
				'pl'=>
					[
						'Poland',
					],
				'pt'=>
					[
						'Portugal',
						'Brazil',
						'Mozambique',
						'Angola',
						'Guinea-Bissau',
						'East Timor',
						'Equatorial Guinea',
						'Macau',
						'Cape Verde',
						'São Tomé and Príncipe',
					],
				'ru'=>
					[
						'Russia',
						'Belarus',
						'Kazakhstan',
						'Kyrgyzstan',
						'Ukraine',
						'Latvia',
						'Moldova',
						'Estonia',
						'Georgia',
						'Armenia',
						'Lithuania',
						'Uzbekistan',
					],
				'tr'=>
					[
						'Turkey',
						'Cyprus',
						'Azerbaijan',
						'Bosnia',
						'Bulgaria',
						'Greece',
						'Iraq',
						'Kosovo',
						'Macedonia',
						'Northern Cyprus',
						'Romania',
					],
				'zh'=>
					[
						'China',
						'Taiwan',
						'Singapore',
					],
			];
		}
		
					// German (DE) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_de()
		{
			return [
				'de'=>
					[
						'Deutschland',
						'Österreich',
						'Schweiz',
						'Liechtenstein',
					],
				'en'=>
					[
						'Vereinigte Staaten von Amerika',
						'Indien',
						'Irland',
						'Pakistan',
						'Nigeria',
						'England',
						'Australia',
						'Kanada',
						'Ghana',
						'Malta',
						'Israel',
						'Neuseeland',
						'Jamaika',
					],
				'es'=>
					[
						'Spanien',
						'Kuba',
						'Mexiko',
						'Kolumbien',
						'Argentinien',
						'Peru',
						'Venezuela',
						'Chile',
						'Ecuador',
						'Guatemala',
						'Bolivien',
						'Dominikanische Republik',
						'Honduras',
						'Paraguay',
						'El Salvador',
						'Nicaragua',
						'Costa Rica',
						'Puerto Rico',
						'Panama',
						'Uruguay',
						'Guyana',
						'Äquatorialguinea',
						'Andorra',
						'Belize',
					],
				'fr'=>
					[
						'Frankreich',
						'Kanada',
						'Madagaskar',
						'Kamerun',
						'Elfenbeinküste',
						'Burkina Faso',
						'Niger',
						'Senegal',
						'Mali',
						'Ruanda',
						'Belgien',
						'Haiti',
						'Chad',
						'Guinea',
						'Burundi',
						'Benin',
						'Schweiz',
						'Gehen',
						'Zentralafrikanische Republik',
						'Republik Kongo',
						'Gabun',
						'Komoren',
						'Äquatorialguinea',
						'Französisch Polynesien',
						'Französisch-Guayana',
						'Neu-Kaledonien',
						'Aostatal',
						'Jersey',
						'Guernsey',
						'Monaco',
						'Saint-Martin',
						'Wallis und Futuna',
						'Saint-Barthélemy',
					],
				'ja'=>
					[
						'Japan',
					],
				'it'=>
					[
						'Italien',
						'Malta',
						'San Marino',
						'Schweiz',
						'Kroatien',
						'Slowenien',
					],
				'nl'=>
					[
						'Niederlande',
						'Belgien',
						'Suriname',
						'Südafrika',
						'Aruba',
						'Curacao',
						'Republic of Namibia',
						'Bonaire',
						'Saba',
						'Sint Eustatius',
						'Sint Maarten',
					],
				'pl'=>
					[
						'Polen',
					],
				'pt'=>
					[
						'Portugal',
						'Brasilien',
						'Mosambik',
						'Angola',
						'Guinea-Bissau',
						'Osttimor',
						'Äquatorialguinea',
						'Macau',
						'Kap Verde',
						'São Tomé und Príncipe',
					],
				'ru'=>
					[
						'Russland',
						'Belarus',
						'Kasachstan',
						'Kirgisien',
						'Ukraine',
						'Lettland',
						'Moldawien',
						'Estland',
						'Georgia',
						'Armenien',
						'Litauen',
						'Usbekistan',
					],
				'tr'=>
					[
						'Truthahn',
						'Zypern',
						'Aserbaidschan',
						'Bosnien',
						'Bulgarien',
						'Griechenland',
						'Irak',
						'Kosovo',
						'Mazedonien',
						'Nord-Zypern',
						'Rumänien',
					],
				'zh'=>
					[
						'China',
						'Taiwan',
						'Singapur',
					],
			];
		}
		
					// Spanish (ES) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_es()
		{
			return [
				'de'=>
					[
						'Alemania',
						'Austria',
						'Suiza',
						'Liechtenstein',
					],
				'en'=>
					[
						'Estados Unidos de America',
						'India',
						'Irlanda',
						'Pakistán',
						'De Nigeria',
						'Inglaterra',
						'Australia',
						'Canadá',
						'Ghana',
						'Malta',
						'Israel',
						'Nueva Zelanda',
						'Jamaica',
					],
				'es'=>
					[
						'España',
						'Cuba',
						'México',
						'Colombia',
						'Argentina',
						'Perú',
						'Venezuela',
						'Chile',
						'Ecuador',
						'Guatemala',
						'Bolivia',
						'República Dominicana',
						'Honduras',
						'Paraguay',
						'El Salvador',
						'Nicaragua',
						'Costa Rica',
						'Puerto Rico',
						'Panamá',
						'Uruguay',
						'Guyana',
						'Guinea Ecuatorial',
						'Andorra',
						'Belice',
					],
				'fr'=>
					[
						'Francia',
						'Canadá',
						'Madagascar',
						'Camerún',
						'Costa de Marfil',
						'Burkina Faso',
						'Niger',
						'Senegal',
						'Mali',
						'Ruanda',
						'Bélgica',
						'Haití',
						'Chad',
						'Guinea',
						'Burundi',
						'Benin',
						'Suiza',
						'Ir',
						'República Centroafricana',
						'República del Congo',
						'Gabón',
						'Comoras',
						'Guinea Ecuatorial',
						'Polinesia francés',
						'Guayana francés',
						'Nueva Caledonia',
						'Valle de Aosta',
						'Jersey',
						'Guernsey',
						'Mónaco',
						'San Martín',
						'Wallis y Futuna',
						'San Bartolomé',
					],
				'ja'=>
					[
						'Japón',
					],
				'it'=>
					[
						'Italia',
						'Malta',
						'San Marino',
						'Suiza',
						'Croacia',
						'Eslovenia',
					],
				'nl'=>
					[
						'Países Bajos',
						'Bélgica',
						'Surinam',
						'Sudáfrica',
						'Aruba',
						'Curazao',
						'República de Namibia',
						'Bonaire',
						'Saba',
						'San Eustaquio',
						'San Martín',
					],
				'pl'=>
					[
						'Polonia',
					],
				'pt'=>
					[
						'Portugal',
						'Brasil',
						'Mozambique',
						'Angola',
						'Guinea-Bissau',
						'Timor Oriental',
						'Guinea Ecuatorial',
						'Macao',
						'Cabo Verde',
						'Santo Tomé y Príncipe',
					],
				'ru'=>
					[
						'Rusia',
						'Belarús',
						'Kazajstán',
						'Kirguistán',
						'Ucrania',
						'Letonia',
						'Moldova',
						'Estonia',
						'Georgia',
						'Armenia',
						'Lituania',
						'Uzbekistán',
					],
				'tr'=>
					[
						'Turquía',
						'Chipre',
						'Azerbaiyán',
						'Bosnia',
						'Bulgaria',
						'Grecia',
						'Irak',
						'Kosovo',
						'Macedonia',
						'El norte de Chipre',
						'Rumania',
					],
				'zh'=>
					[
						'China',
						'Taiwán',
						'Singapur',
					],
			];
		}
		
					// French (FR) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_fr()
		{
			return [
				'de'=>
					[
						'Allemagne',
						'Autriche',
						'Suisse',
						'Le Liechtenstein',
					],
				'en'=>
					[
						'Etats-Unis d\'Amerique',
						'Inde',
						'Irlande',
						'Pakistan',
						'Nigeria',
						'Angleterre',
						'Australie',
						'Canada',
						'Ghana',
						'Malte',
						'Israël',
						'Nouvelle Zélande',
						'Jamaïque',
					],
				'es'=>
					[
						'L\'Espagne',
						'Cuba',
						'Mexique',
						'Colombie',
						'Argentine',
						'Pérou',
						'Venezuela',
						'Chili',
						'Équateur',
						'Guatemala',
						'Bolivie',
						'République Dominicaine',
						'Honduras',
						'Paraguay',
						'Le Salvador',
						'Nicaragua',
						'Costa Rica',
						'Puerto Rico',
						'Panama',
						'Uruguay',
						'Guyana',
						'Guinée Équatoriale',
						'Andorre',
						'Belize',
					],
				'fr'=>
					[
						'France',
						'Canada',
						'Madagascar',
						'Cameroun',
						'Côte d\'Ivoire',
						'Burkina Faso',
						'Niger',
						'Sénégal',
						'Mali',
						'Rwanda',
						'Belgique',
						'Haïti',
						'Tchad',
						'Guinée',
						'Burundi',
						'Bénin',
						'Suisse',
						'Aller',
						'République centrafricaine',
						'République du Congo',
						'Gabon',
						'Comores',
						'Guinée Équatoriale',
						'Polynésie française',
						'Guinée Française',
						'Nouvelle Calédonie',
						'Vallée d\'Aoste',
						'Jersey',
						'Guernsey',
						'Monaco',
						'Saint Martin',
						'Wallis et Futuna',
						'Saint-Barthélemy',
					],
				'ja'=>
					[
						'Japon',
					],
				'it'=>
					[
						'Italie',
						'Malte',
						'Saint Marin',
						'Suisse',
						'Croatie',
						'Slovénie',
					],
				'nl'=>
					[
						'Pays-Bas',
						'Belgique',
						'Suriname',
						'Afrique du Sud',
						'Aruba',
						'Curacao',
						'République de Namibie',
						'Bonaire',
						'Saba',
						'Sint Eustatius',
						'Sint Maarten',
					],
				'pl'=>
					[
						'Pologne',
					],
				'pt'=>
					[
						'Le Portugal',
						'Brésil',
						'Mozambique',
						'Angola',
						'Guinée-Bissau',
						'Timor oriental',
						'Guinée Équatoriale',
						'Macao',
						'Cap-Vert',
						'São Tomé et Príncipe',
					],
				'ru'=>
					[
						'Russie',
						'Belarus',
						'Kazakhstan',
						'Kirghizistan',
						'Ukraine',
						'Lettonie',
						'Moldova',
						'Estonie',
						'Géorgie',
						'Arménie',
						'Lituanie',
						'Ouzbékistan',
					],
				'tr'=>
					[
						'Dinde',
						'Chypre',
						'Azerbaïdjan',
						'Bosnie',
						'Bulgarie',
						'Grèce',
						'Irak',
						'Kosovo',
						'Macédoine',
						'Chypre du Nord',
						'Roumanie',
					],
				'zh'=>
					[
						'Chine',
						'Taïwan',
						'Singapour',
					],
			];
		}
		
					// Japanese (JA) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_ja()
		{
			return [
				'de'=>
					[
						'ドイツ',
						'オーストリア',
						'スイス',
						'リヒテンシュタイン',
					],
				'en'=>
					[
						'アメリカ合衆国',
						'インド',
						'アイルランド',
						'パキスタン',
						'ナイジェリア',
						'イングランド',
						'オーストラリア',
						'カナダ',
						'ガーナ',
						'マルタ',
						'イスラエル',
						'ニュージーランド',
						'ジャマイカ',
					],
				'es'=>
					[
						'スペイン',
						'キューバ',
						'メキシコ',
						'コロンビア',
						'アルゼンチン',
						'ペルー',
						'ベネズエラ',
						'チリ',
						'エクアドル',
						'グアテマラ',
						'ボリビア',
						'ドミニカ共和国',
						'ホンジュラス',
						'パラグアイ',
						'エルサルバドル',
						'ニカラグア',
						'コスタリカ',
						'プエルトリコ',
						'パナマ',
						'ウルグアイ',
						'ガイアナ',
						'赤道ギニア',
						'アンドラ',
						'ベリーズ',
					],
				'fr'=>
					[
						'フランス',
						'カナダ',
						'マダガスカル',
						'カメルーン',
						'コートジボワール',
						'ブルキナファソ',
						'ニジェール',
						'セネガル',
						'マリ',
						'ルワンダ',
						'ベルギー',
						'ハイチ',
						'チャド',
						'ギニア',
						'ブルンジ',
						'ベニン',
						'スイス',
						'行く',
						'中央アフリカ共和国',
						'コンゴ共和国',
						'ガボン',
						'コモロ',
						'赤道ギニア',
						'フランス領ポリネシア',
						'仏領ギアナ',
						'ニューカレドニア',
						'ヴァッレ・ダオスタ州',
						'ジャージー',
						'ガーンジー島',
						'モナコ',
						'サン・マルタン',
						'ワリー・エ・フトゥーナ',
						'サン・バルテルミー島',
					],
				'ja'=>
					[
						'日本',
					],
				'it'=>
					[
						'イタリア',
						'マルタ',
						'サン・マリノ',
						'スイス',
						'クロアチア',
						'スロベニア',
					],
				'nl'=>
					[
						'オランダ',
						'ベルギー',
						'スリナム',
						'南アフリカ',
						'アルバ',
						'キュラソー',
						'ナミビア共和国',
						'ボネール島',
						'サバ',
						'セントユースタティウス',
						'シントマールテン島',
					],
				'pl'=>
					[
						'ポーランド',
					],
				'pt'=>
					[
						'ポルトガル',
						'ブラジル',
						'モザンビーク',
						'アンゴラ',
						'ギニアビサウ',
						'東ティモール',
						'赤道ギニア',
						'マカオ',
						'カーボベルデ',
						'サントメプリンシペ',
					],
				'ru'=>
					[
						'ロシア',
						'ベラルーシ',
						'カザフスタン',
						'キルギスタン',
						'ウクライナ',
						'ラトビア',
						'モルドバ',
						'エストニア',
						'ジョージア',
						'アルメニア',
						'リトアニア',
						'ウズベキスタン',
					],
				'tr'=>
					[
						'七面鳥',
						'キプロス',
						'アゼルバイジャン',
						'ボスニア',
						'ブルガリア',
						'ギリシャ',
						'イラク',
						'コソボ',
						'マケドニア',
						'北キプロス',
						'ルーマニア',
					],
				'zh'=>
					[
						'中国',
						'台湾',
						'シンガポール',
					],
			];
		}
		
					// Italian (IT) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_it()
		{
			return [
				'de'=>
					[
						'Germania',
						'Austria',
						'Svizzera',
						'Liechtenstein',
					],
				'en'=>
					[
						'Stati Uniti d\'America',
						'India',
						'Irlanda',
						'Pakistan',
						'Nigeria',
						'Inghilterra',
						'Australia',
						'Canada',
						'Ghana',
						'Malta',
						'Israele',
						'Nuova Zelanda',
						'Giamaica',
					],
				'es'=>
					[
						'Spagna',
						'Cuba',
						'Messico',
						'Colombia',
						'Argentina',
						'Perù',
						'Venezuela',
						'Chile',
						'Ecuador',
						'Guatemala',
						'Bolivia',
						'Repubblica Dominicana',
						'Honduras',
						'Paraguay',
						'El Salvador',
						'Nicaragua',
						'Costa Rica',
						'Puerto Rico',
						'Panama',
						'Uruguay',
						'Guyana',
						'Guinea Equatoriale',
						'Andorra',
						'Belize',
					],
				'fr'=>
					[
						'Francia',
						'Canada',
						'Madagascar',
						'Camerun',
						'Costa d\'Avorio',
						'Burkina Faso',
						'Niger',
						'Senegal',
						'Mali',
						'Ruanda',
						'Belgio',
						'Haiti',
						'Chad',
						'Guinea',
						'Burundi',
						'Benin',
						'Svizzera',
						'Andare',
						'Repubblica Centrafricana',
						'Repubblica del Congo',
						'Gabon',
						'Comore',
						'Guinea Equatoriale',
						'Polinesia francese',
						'Guiana francese',
						'Nuova Caledonia',
						'Valle d\'Aosta',
						'Maglia',
						'Maglione',
						'Monaco',
						'Saint-Martin',
						'Wallis e Futuna',
						'Saint-Barthélemy',
					],
				'ja'=>
					[
						'Giappone',
					],
				'it'=>
					[
						'Italia',
						'Malta',
						'San Marino',
						'Svizzera',
						'Croazia',
						'Slovenia',
					],
				'nl'=>
					[
						'Olanda',
						'Belgio',
						'Suriname',
						'Sud Africa',
						'Aruba',
						'Curacao',
						'Repubblica di Namibia',
						'Bonaire',
						'Saba',
						'Sint Eustatius',
						'Sint Maarten',
					],
				'pl'=>
					[
						'Polonia',
					],
				'pt'=>
					[
						'Portogallo',
						'Brasile',
						'Mozambico',
						'Angola',
						'Guinea-Bissau',
						'Timor Est',
						'Guinea Equatoriale',
						'Macau',
						'Capo Verde',
						'Sao Tome e Principe',
					],
				'ru'=>
					[
						'Russia',
						'Bielorussia',
						'Kazakhstan',
						'Kyrgyzstan',
						'Ucraina',
						'Lettonia',
						'Moldova',
						'Estonia',
						'Georgia',
						'Armenia',
						'Lituania',
						'Uzbekistan',
					],
				'tr'=>
					[
						'Tacchino',
						'Cipro',
						'Azerbaijan',
						'Bosnia',
						'Bulgaria',
						'Grecia',
						'Iraq',
						'Kosovo',
						'Macedonia',
						'Cipro del Nord',
						'Romania',
					],
				'zh'=>
					[
						'Cina',
						'Taiwan',
						'Singapore',
					],
			];
		}
		
					// Dutch (NL) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_nl()
		{
			return [
				'de'=>
					[
						'Duitsland',
						'Oostenrijk',
						'Zwitserland',
						'Liechtenstein',
					],
				'en'=>
					[
						'de Verenigde Staten van Amerika',
						'Indië',
						'Ierland',
						'Pakistan',
						'Nigeria',
						'Engeland',
						'Australië',
						'Canada',
						'Ghana',
						'Malta',
						'Israël',
						'Nieuw Zeeland',
						'Jamaica',
					],
				'es'=>
					[
						'Spanje',
						'Cuba',
						'Mexico',
						'Colombia',
						'Argentinië',
						'Peru',
						'Venezuela',
						'Chili',
						'Ecuador',
						'Guatemala',
						'Bolivia',
						'Dominicaanse Republiek',
						'Honduras',
						'Paraguay',
						'El Salvador',
						'Nicaragua',
						'Costa Rica',
						'Puerto Rico',
						'Panama',
						'Uruguay',
						'Guyana',
						'Equatoriaal-Guinea',
						'Andorra',
						'Belize',
					],
				'fr'=>
					[
						'Frankrijk',
						'Canada',
						'Madagascar',
						'Kameroen',
						'Ivoorkust',
						'Burkina Faso',
						'Niger',
						'Senegal',
						'Mali',
						'Rwanda',
						'België',
						'Haïti',
						'Tsjaad',
						'Guinea',
						'Boeroendi',
						'Benin',
						'Zwitserland',
						'Gaan',
						'Centraal Afrikaanse Republiek',
						'Republiek Congo',
						'Gabon',
						'Comoren',
						'Equatoriaal-Guinea',
						'Frans-Polynesië',
						'Frans-Guyana',
						'Nieuw-Caledonië',
						'Valle d\'Aosta',
						'Jersey',
						'Guernsey',
						'Monaco',
						'Saint-Martin',
						'Wallis en Futuna',
						'Saint-Barthélemy',
					],
				'ja'=>
					[
						'Japan',
					],
				'it'=>
					[
						'Italië',
						'Malta',
						'San Marino',
						'Zwitserland',
						'Kroatië',
						'Slovenië',
					],
				'nl'=>
					[
						'Nederland',
						'België',
						'Suriname',
						'Zuid-Afrika',
						'Aruba',
						'Curaçao',
						'Republiek Namibië',
						'Bonaire',
						'Saba',
						'Sint Eustatius',
						'Sint Maarten',
					],
				'pl'=>
					[
						'Polen',
					],
				'pt'=>
					[
						'Portugal',
						'Brazilië',
						'Mozambique',
						'Angola',
						'Guinee-Bissau',
						'Oost Timor',
						'Equatoriaal-Guinea',
						'Macau',
						'Kaapverdië',
						'São Tomé en Príncipe',
					],
				'ru'=>
					[
						'Rusland',
						'Wit-Rusland',
						'Kazachstan',
						'Kirgizië',
						'Oekraïne',
						'Letland',
						'Moldavië',
						'Estland',
						'Georgia',
						'Armenië',
						'Litouwen',
						'Oezbekistan',
					],
				'tr'=>
					[
						'Turkije',
						'Cyprus',
						'Azerbeidzjan',
						'Bosnië',
						'Bulgarije',
						'Griekenland',
						'Irak',
						'Kosovo',
						'Macedonië',
						'Noord-Cyprus',
						'Roemenië',
					],
				'zh'=>
					[
						'China',
						'Taiwan',
						'Singapore',
					],
			];
		}
		
					// Polish (PL) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_pl()
		{
			return [
				'de'=>
					[
						'Niemcy',
						'Austria',
						'Szwajcaria',
						'Liechtenstein',
					],
				'en'=>
					[
						'Stany Zjednoczone Ameryki',
						'Indie',
						'Irlandia',
						'Pakistan',
						'Nigeria',
						'Anglia',
						'Australia',
						'Kanada',
						'Ghana',
						'Malta',
						'Izrael',
						'Nowa Zelandia',
						'Jamaica',
					],
				'es'=>
					[
						'Hiszpania',
						'Kuba',
						'Meksyk',
						'Kolumbia',
						'Argentyna',
						'Peru',
						'Wenezuela',
						'Chile',
						'Ekwador',
						'Gwatemala',
						'Boliwia',
						'Republika Dominikany',
						'Honduras',
						'Paragwaj',
						'Salwador',
						'Nikaragua',
						'Kostaryka',
						'Portoryko',
						'Panama',
						'Urugwaj',
						'Gujana',
						'Gwinea Równikowa',
						'Andorra',
						'Belize',
					],
				'fr'=>
					[
						'Francja',
						'Kanada',
						'Madagaskar',
						'Kamerun',
						'Wybrzeże Kości Słoniowej',
						'Burkina Faso',
						'Niger',
						'Senegal',
						'Mali',
						'Rwandy',
						'Belgia',
						'Haiti',
						'Czad',
						'Gwinea',
						'Burundi',
						'Benin',
						'Szwajcaria',
						'Iść',
						'Republika Środkowoafrykańska',
						'Republika Konga',
						'Gabon',
						'Komory',
						'Gwinea Równikowa',
						'Polinezja Francuska',
						'Gujana Francuska',
						'Nowa Kaledonia',
						'Dolina Aosty',
						'Jersey',
						'Guernsey',
						'Monaco',
						'Saint-Martin',
						'Wallis i Futuna',
						'Saint-Barthélemy',
					],
				'ja'=>
					[
						'Japonia',
					],
				'it'=>
					[
						'Włochy',
						'Malta',
						'San Marino',
						'Szwajcaria',
						'Chorwacja',
						'Słowenia',
					],
				'nl'=>
					[
						'Holandia',
						'Belgia',
						'Surinam',
						'Afryka Południowa',
						'Aruba',
						'Curacao',
						'Republika Namibii',
						'Bonaire',
						'Saba',
						'Sint Eustatius',
						'Sint Maarten',
					],
				'pl'=>
					[
						'Polska',
					],
				'pt'=>
					[
						'Portugalia',
						'Brazylia',
						'Mozambik',
						'Angola',
						'Gwinea Bissau',
						'Wschodni Timor',
						'Gwinea Równikowa',
						'Macau',
						'Wyspy Zielonego Przylądka',
						'Świętego Tomasza i Książęca',
					],
				'ru'=>
					[
						'Rosja',
						'Białoruś',
						'Kazachstan',
						'Kirgistan',
						'Ukraina',
						'Łotwa',
						'Mołdawia',
						'Estonia',
						'Gruzja',
						'Armenia',
						'Litwa',
						'Uzbekistan',
					],
				'tr'=>
					[
						'Indyk',
						'Cypr',
						'Azerbejdżan',
						'Bośnia',
						'Bułgaria',
						'Grecja',
						'Irak',
						'Kosowo',
						'Macedonia',
						'Cypr Północny',
						'Rumunia',
					],
				'zh'=>
					[
						'Chiny',
						'Tajwan',
						'Singapur',
					],
			];
		}
		
					// Portuguese (PT) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_pt()
		{
			return [
				'de'=>
					[
						'Alemanha',
						'Áustria',
						'Suíça',
						'Liechtenstein',
					],
				'en'=>
					[
						'Estados Unidos da America',
						'Índia',
						'Irlanda',
						'Paquistão',
						'Nigéria',
						'Inglaterra',
						'Austrália',
						'Canadá',
						'Gana',
						'Malta',
						'Israel',
						'Nova Zelândia',
						'Jamaica',
					],
				'es'=>
					[
						'Espanha',
						'Cuba',
						'México',
						'Colômbia',
						'Argentina',
						'Peru',
						'Venezuela',
						'Chile',
						'Equador',
						'Guatemala',
						'Bolívia',
						'República Dominicana',
						'Honduras',
						'Paraguai',
						'El Salvador',
						'Nicarágua',
						'Costa Rica',
						'Porto Rico',
						'Panamá',
						'Uruguai',
						'Guiana',
						'Guiné Equatorial',
						'Andorra',
						'Belize',
					],
				'fr'=>
					[
						'França',
						'Canadá',
						'Madagáscar',
						'Camarões',
						'Costa do Marfim',
						'Burkina Faso',
						'Níger',
						'Senegal',
						'Mali',
						'Ruanda',
						'Bélgica',
						'Haiti',
						'Chade',
						'Guiné',
						'Burundi',
						'Benin',
						'Suíça',
						'Ir',
						'Central Africano República',
						'República do Congo',
						'Gabão',
						'Comores',
						'Guiné Equatorial',
						'Polinésia Francesa',
						'Guiana Francesa',
						'Nova Caledônia',
						'Vale de Aosta',
						'Camisola',
						'Guernsey',
						'Monaco',
						'Saint-Martin',
						'Wallis e Futuna',
						'Saint-Barthélemy',
					],
				'ja'=>
					[
						'Japão',
					],
				'it'=>
					[
						'Itália',
						'Malta',
						'San Marino',
						'Suíça',
						'Croácia',
						'Eslovenia',
					],
				'nl'=>
					[
						'Países Baixos',
						'Bélgica',
						'Suriname',
						'África do Sul',
						'Aruba',
						'Curaçao',
						'República da Namíbia',
						'Bonaire',
						'Saba',
						'Sint Eustatius',
						'Sint Maarten',
					],
				'pl'=>
					[
						'Polônia',
					],
				'pt'=>
					[
						'Portugal',
						'Brasil',
						'Moçambique',
						'Angola',
						'Guiné-Bissau',
						'Timor Leste',
						'Guiné Equatorial',
						'Macau',
						'Cabo Verde',
						'São Tomé e Príncipe',
					],
				'ru'=>
					[
						'Rússia',
						'Belarus',
						'Cazaquistão',
						'Quirguistão',
						'Ucrânia',
						'Letônia',
						'Moldova',
						'Estônia',
						'Georgia',
						'Armênia',
						'Lituânia',
						'Uzbequistão',
					],
				'tr'=>
					[
						'Peru',
						'Chipre',
						'Azerbaijão',
						'Bósnia',
						'Bulgária',
						'Grécia',
						'Iraque',
						'Kosovo',
						'Macedónia',
						'Chipre do Norte',
						'Romênia',
					],
				'zh'=>
					[
						'China',
						'Taiwan',
						'Cingapura',
					],
			];
		}
		
					// Russian (RU) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_ru()
		{
			return [
				'de'=>
					[
						'Германия',
						'Австрия',
						'Швейцария',
						'Лихтенштейн',
					],
				'en'=>
					[
						'Соединенные Штаты Америки',
						'Индия',
						'Ирландия',
						'Пакистан',
						'Нигерия',
						'Англия',
						'Австралия',
						'Канада',
						'Гана',
						'Мальта',
						'Израиль',
						'Новая Зеландия',
						'Ямайка',
					],
				'es'=>
					[
						'Испания',
						'Куба',
						'Мексика',
						'Колумбия',
						'Аргентина',
						'Перу',
						'Венесуэла',
						'Чили',
						'Эквадор',
						'Гватемала',
						'Боливия',
						'Доминиканская Республика',
						'Гондурас',
						'Парагвай',
						'Сальвадор',
						'Никарагуа',
						'Коста-Рика',
						'Пуэрто-Рико',
						'Панама',
						'Уругвай',
						'Гайана',
						'Экваториальная Гвинея',
						'андорра',
						'Белиз',
					],
				'fr'=>
					[
						'Франция',
						'Канада',
						'Мадагаскар',
						'Камерун',
						'Кот-д\'Ивуар',
						'Буркина-Фасо',
						'Нигер',
						'Сенегал',
						'Мали',
						'Руанда',
						'Бельгия',
						'Гаити',
						'Чад',
						'Гвинея',
						'Бурунди',
						'Бенин',
						'Швейцария',
						'Идти',
						'Центрально-Африканская Республика',
						'Республика Конго',
						'Габон',
						'Коморские острова',
						'Экваториальная Гвинея',
						'Французская Полинезия',
						'Французская Гвиана',
						'Новая Каледония',
						'д\'Аоста',
						'Джерси',
						'шерстяная фуфайка',
						'Монако',
						'Сен-Мартен',
						'Уоллис и Футуна',
						'Сен-Бартельми',
					],
				'ja'=>
					[
						'Япония',
					],
				'it'=>
					[
						'Италия',
						'Мальта',
						'Сан - Марино',
						'Швейцария',
						'Хорватия',
						'Словения',
					],
				'nl'=>
					[
						'Нидерланды',
						'Бельгия',
						'Суринам',
						'Южная Африка',
						'Аруба',
						'Кюрасао',
						'Республика Намибия',
						'Бонайре',
						'Саба',
						'Синт-Эстатиус',
						'Синт-Маартен',
					],
				'pl'=>
					[
						'Польша',
					],
				'pt'=>
					[
						'Португалия',
						'Бразилия',
						'Мозамбик',
						'Ангола',
						'Гвинея-Бисау',
						'Восточный Тимор',
						'Экваториальная Гвинея',
						'Макао',
						'Кабо-Верде',
						'Сан-Томе и Принсипи',
					],
				'ru'=>
					[
						'Россия',
						'Беларусь',
						'Казахстан',
						'Киргизия',
						'Украина',
						'Латвия',
						'Молдова',
						'Эстония',
						'Грузия',
						'Армения',
						'Литва',
						'Узбекистан',
					],
				'tr'=>
					[
						'Турция',
						'Кипр',
						'Азербайджан',
						'Босния',
						'Болгария',
						'Греция',
						'Ирак',
						'Косово',
						'Македония',
						'Северный Кипр',
						'Румыния',
					],
				'zh'=>
					[
						'Китай',
						'Тайвань',
						'Сингапур',
					],
			];
		}
		
					// Turkish (TR) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_tr()
		{
			return [
				'de'=>
					[
						'Almanya',
						'Avusturya',
						'İsviçre',
						'Liechtenstein',
					],
				'en'=>
					[
						'Amerika Birleşik Devletleri',
						'Hindistan',
						'İrlanda',
						'Pakistan',
						'Nijerya',
						'İngiltere',
						'Avustralya',
						'Kanada',
						'Gana',
						'Malta',
						'İsrail',
						'Yeni Zelanda',
						'Jamaika',
					],
				'es'=>
					[
						'Ispanya',
						'Küba',
						'Meksika',
						'Kolombiya',
						'Arjantin',
						'Peru',
						'Venezuela',
						'Şili',
						'Ekvador',
						'Guatemala',
						'Bolivya',
						'Dominik Cumhuriyeti',
						'Honduras',
						'Paraguay',
						'El Salvador',
						'Nikaragua',
						'Kostarika',
						'Porto Riko',
						'Panama',
						'Uruguay',
						'Guyana',
						'Ekvator Ginesi',
						'Andorra',
						'Belize',
					],
				'fr'=>
					[
						'Fransa',
						'Kanada',
						'Madagaskar',
						'Kamerun',
						'Fildişi Sahili',
						'Burkina Faso',
						'Nijer',
						'Senegal',
						'Mali',
						'Ruanda',
						'Belçika',
						'Haiti',
						'Çad',
						'Gine',
						'Burundi',
						'Benin',
						'İsviçre',
						'Gitmek',
						'Orta Afrika Cumhuriyeti',
						'Kongo Cumhuriyeti',
						'Gabon',
						'Komorlar',
						'Ekvator Ginesi',
						'Fransız Polinezyası',
						'Fransız Guyanası',
						'Yeni Kaledonya',
						'Aosta Vadisi',
						'Jersey',
						'Bir Tür Inek',
						'Monako',
						'Saint-Martin',
						'Wallis ve Futuna',
						'Saint-Barthelemy',
					],
				'ja'=>
					[
						'Japonya',
					],
				'it'=>
					[
						'İtalya',
						'Malta',
						'San Marino',
						'İsviçre',
						'Hırvatistan',
						'Slovenya',
					],
				'nl'=>
					[
						'Hollanda',
						'Belçika',
						'Surinam',
						'Güney Afrika',
						'Aruba',
						'Curacao',
						'Namibya Cumhuriyeti',
						'Bonaire',
						'Saba',
						'Sint Eustatius',
						'Sint Maarten',
					],
				'pl'=>
					[
						'Polonya',
					],
				'pt'=>
					[
						'Portekiz',
						'Brezilya',
						'Mozambik',
						'Angora',
						'Gine-Bissau',
						'Doğu Timor',
						'Ekvator Ginesi',
						'Makao',
						'Cape Verde',
						'Sao Tome ve Principe',
					],
				'ru'=>
					[
						'Rusya',
						'Belarus',
						'Kazakistan',
						'Kırgızistan',
						'Ukrayna',
						'Letonya',
						'Moldova',
						'Estonya',
						'Gürcistan',
						'Ermenistan',
						'Litvanya',
						'Özbekistan',
					],
				'tr'=>
					[
						'Türkiye',
						'Kıbrıs',
						'Azerbeycan',
						'Bosna',
						'Bulgaristan',
						'Yunanistan',
						'Irak',
						'Kosova',
						'Makedonya',
						'Kuzey Kıbrıs',
						'Romanya',
					],
				'zh'=>
					[
						'Çin',
						'Tayvan',
						'Singapur',
					],
			];
		}
		
					// Chinese (ZH) Accessor
					// ------------------------------------------------------------------------
		
		public function GetTranslatedCountryNames_zh()
		{

			return [
				'de'=>
					[
						'德国',
						'奥地利',
						'瑞士',
						'列支敦士登',
					],
				'en'=>
					[
						'美国',
						'印度',
						'爱尔兰',
						'巴基斯坦',
						'尼日利亚',
						'英格兰',
						'澳大利亚',
						'加拿大',
						'加纳',
						'马耳他',
						'以色列',
						'新西兰',
						'牙买加',
					],
				'es'=>
					[
						'西班牙',
						'古巴',
						'墨西哥',
						'哥伦比亚',
						'阿根廷',
						'秘鲁',
						'委内瑞拉',
						'智利',
						'厄瓜多尔',
						'危地马拉',
						'玻利维亚',
						'多明尼加共和国',
						'洪都拉斯',
						'巴拉圭',
						'萨尔瓦多',
						'尼加拉瓜',
						'哥斯达黎加',
						'波多黎各',
						'巴拿马',
						'乌拉圭',
						'圭亚那',
						'赤道几内亚',
						'安道尔',
						'伯利兹',
					],
				'fr'=>
					[
						'法国',
						'加拿大',
						'马达加斯加',
						'喀麦隆',
						'象牙海岸',
						'布基纳法索',
						'尼日尔',
						'塞内加尔',
						'马里',
						'卢旺达',
						'比利时',
						'海地',
						'乍得',
						'几内亚',
						'布隆迪',
						'贝宁',
						'瑞士',
						'多哥',
						'中非共和国',
						'刚果民主共和国',
						'加蓬',
						'科摩罗',
						'赤道几内亚',
						'法属波利尼西亚',
						'法属圭亚那',
						'新喀里多尼亚',
						'奥斯塔山谷',
						'新泽西',
						'根西岛',
						'摩纳哥',
						'圣马丁',
						'瓦利斯和富图纳群岛',
						'圣巴泰勒米',
					],
				'ja'=>
					[
						'日本',
					],
				'it'=>
					[
						'意大利',
						'马耳他',
						'圣马力诺',
						'瑞士',
						'克罗地亚',
						'斯洛文尼亚',
					],
				'nl'=>
					[
						'荷兰',
						'比利时',
						'苏里南',
						'南非',
						'阿鲁巴',
						'库拉索',
						'纳米比亚共和国',
						'博内尔',
						'萨巴',
						'圣尤斯特歇斯',
						'圣马丁岛',
					],
				'pl'=>
					[
						'波兰',
					],
				'pt'=>
					[
						'葡萄牙',
						'巴西',
						'莫桑比克',
						'安哥拉',
						'几内亚比绍',
						'东帝汶',
						'赤道几内亚',
						'澳门',
						'佛得角',
						'圣多美和普林西比',
					],
				'ru'=>
					[
						'俄国',
						'白俄罗斯',
						'哈萨克斯坦',
						'吉尔吉斯斯坦',
						'乌克兰',
						'拉脱维亚',
						'摩尔多瓦',
						'爱沙尼亚',
						'格鲁吉亚',
						'亚美尼亚',
						'立陶宛',
						'乌兹别克斯坦',
					],
				'tr'=>
					[
						'火鸡',
						'塞浦路斯',
						'阿塞拜疆',
						'波斯尼亚',
						'保加利亚',
						'希腊',
						'伊拉克',
						'科索沃',
						'马其顿',
						'北塞浦路斯',
						'罗马尼亚',
					],
				'zh'=>
					[
						'中国',
						'台湾',
						'新加坡',
					],
			];
		}
	}
	
?>